// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOepbmh5lGcm--t2Z-_jM9UtCRKGh3JQI',
    appId: '1:704542458502:web:2dfa5f13c9ea5681c54707',
    messagingSenderId: '704542458502',
    projectId: 'civilization-timeline',
    authDomain: 'civilization-timeline.firebaseapp.com',
    storageBucket: 'civilization-timeline.firebasestorage.app',
    measurementId: 'G-XLVJQPKZD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLfHsSYmt8EhKx1Amer65jns2aa72DqHY',
    appId: '1:704542458502:android:37078df5f0fa9415c54707',
    messagingSenderId: '704542458502',
    projectId: 'civilization-timeline',
    storageBucket: 'civilization-timeline.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKgC39HdvJZy93qHuc82EkEbpWsLTlkQM',
    appId: '1:704542458502:ios:699d74b09c328ad2c54707',
    messagingSenderId: '704542458502',
    projectId: 'civilization-timeline',
    storageBucket: 'civilization-timeline.firebasestorage.app',
    iosBundleId: 'com.antikmedeniyetler.civilizationTimelineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKgC39HdvJZy93qHuc82EkEbpWsLTlkQM',
    appId: '1:704542458502:ios:699d74b09c328ad2c54707',
    messagingSenderId: '704542458502',
    projectId: 'civilization-timeline',
    storageBucket: 'civilization-timeline.firebasestorage.app',
    iosBundleId: 'com.antikmedeniyetler.civilizationTimelineApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOepbmh5lGcm--t2Z-_jM9UtCRKGh3JQI',
    appId: '1:704542458502:web:2bb60589b685ca04c54707',
    messagingSenderId: '704542458502',
    projectId: 'civilization-timeline',
    authDomain: 'civilization-timeline.firebaseapp.com',
    storageBucket: 'civilization-timeline.firebasestorage.app',
    measurementId: 'G-SEH93L95MT',
  );

}

// ⚠️ IMPORTANT: This is a placeholder file!
// Run 'flutterfire configure' to generate the actual configuration
// with your Firebase project credentials.